title: chen-xiuwei  #标题
email: cxw2772809425@163.com
description: |
  TYUT计科17级在读<br/>
  <a href="https://github.com/chen-xiuwei">
    <i class="fab fa-github"></i>
  </a>
url: https://chen-xiuwei.github.io
baseurl: ""



author:
  name: chen-xiuwei
  description: TYUT计科17级在读
  gravatar:  a259451310e45dc6666a057d4a3123d9            #自己的md5码
  contact:
    github:    https://github.com/chen-xiuwei
    # facebook:  <hide>
    email:     cxw2772809425@163.com

body:
            theme-base: theme-base-07 # 可选的主题色包括08~0f，见 <https://github.com/poole/lanyon>
            layout-reverse: true # 开启后sidebar在右边，反之左边
            sidebar-overlay: true # 开启后正文不随sidebar移动而移动
 append_to_head: # 通过内嵌html的方式引入并定制插件，删改前确定知道自己在做什么。定制插件的方式可以参考这篇文章 <https://wu-kan.cn/_posts/2019-01-18-基于Jekyll搭建个人博客/>
            - | #一些页面优化标签，看不懂可跳过
              <meta
                name="viewport"
                content="width=device-width,minimum-scale=1,initial-scale=1"
              />
              <meta
                http-equiv="content-type"
                content="text/html; charset=utf-8"
              />
              <link
                rel="alternate"
                href="/feed.xml"
                title="RSS"
                type="application/rss+xml"
              />
            - | # 网站小图标，可换成你自己的图片，改href中的部分即可
              <link
                rel="apple-touch-icon-precomposed"
                href="https://gravatar.loli.net/avatar/289efba375d63424de3c49569c446744?s=320"
              />
              <link
                rel="shortcut
                icon"
                href="https://gravatar.loli.net/avatar/289efba375d63424de3c49569c446744?s=32"
              />






#下面这一段为博客的相关路径设置
nav:
  个人介绍:
    - '/about/'
  博客:
    - '/blog/'
    - {分类: '/blog/categories/'}
    - {标签: '/blog/tags/'}

paginate: 5
paginate_path: '/blog/page:num'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


compress_html: # <https://github.com/penibelst/jekyll-compress-html>
  clippings: all
  comments: [] # 注释不能压缩，否则 reveal.js 的 ppt切屏受影响
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Build settings

plugins:
  - jekyll-feed
  - jekyll-paginate

readme_index: # 缺失index.md和index.html时，使用README.md代替之
  with_frontmatter: true # 支持带有yaml头的README

webmaster_verifications: # <https://jekyll.github.io/jekyll-seo-tag/usage/>
  google: YIKi1rBnyUaS-DMYiluseI5kZzTwjCkTFmKkSkMZDJk
  baidu: szbTSfUGAB

permalink: /:categories/:year-:month-:day-:title/ #生成文章的地址格式，我希望它和_posts目录下的格式一样

future: true # 允许发布时间在未来的文章
encoding: utf-8

markdown: kramdown
kramdown: # 见<https://kramdown.gettalong.org/options.html>
  input: GFM # 见<http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # 可见<https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    block:
      disable: true # 关掉代码块默认的高亮，换用prismjs
      line_numbers: false #渲染出来的效果好鬼畜
    span:
      disable: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
