title: chen-xiuwei  #标题
email: cxw2772809425@163.com
description: |
  TYUT计科17级在读<br/>
  <a href="https://github.com/chen-xiuwei">
    <i class="fab fa-github"></i>
  </a>
url: https://chen-xiuwei.github.io




author:
  name: chen-xiuwei
  description: TYUT计科17级在读
  gravatar:              #自己的md5码
  contact:
    github: https://chen-xiuwei.github.io
    email: cxw2772809425@163.com





#下面这一段为博客的相关路径设置
nav:
  Blog:
    - 'blog/'
    - {Categories: '/blog/categories/'}
    - {Tages: '/blog/tags/'}



compress_html: # <https://github.com/penibelst/jekyll-compress-html>
  clippings: all
  comments: [] # 注释不能压缩，否则 reveal.js 的 ppt切屏受影响
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Build settings

plugins:
  - jekyll-feed
  - jekyll-paginate

readme_index: # 缺失index.md和index.html时，使用README.md代替之
  with_frontmatter: true # 支持带有yaml头的README

webmaster_verifications: # <https://jekyll.github.io/jekyll-seo-tag/usage/>
  google: YIKi1rBnyUaS-DMYiluseI5kZzTwjCkTFmKkSkMZDJk
  baidu: szbTSfUGAB

permalink: /:categories/:year-:month-:day-:title/ #生成文章的地址格式，我希望它和_posts目录下的格式一样

future: true # 允许发布时间在未来的文章
encoding: utf-8

markdown: kramdown
kramdown: # 见<https://kramdown.gettalong.org/options.html>
  input: GFM # 见<http://jekyllcn.com/docs/configuration/#kramdown>
  syntax_highlighter_opts: # 可见<https://kramdown.gettalong.org/syntax_highlighter/rouge.html>
    block:
      disable: true # 关掉代码块默认的高亮，换用prismjs
      line_numbers: false #渲染出来的效果好鬼畜
    span:
      disable: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
